### ISSUE TITLE
「小惑星データ更新」

### ISSUE THREAD

**Issue by Mizunanari** [coias/coias-back-app#16]
「小惑星データ更新」というボタン名でgetMPCORB_and_mpc2edbスクリプト叩けるようなボタンの実装

場所は探索準備モードの画面のどこかに、孤立する形で置いていただければ良いかと思います。(全自動処理の右の方、自動検出の上あたり?)

**Comment by COIAS-program** [comment]
エラーハンドリングもできるように専用のスクリプトを作成いたしましたので、「小惑星データ更新」ボタンを探索準備モードにおいていただいたら、以下のスクリプトを叩くようにお願い致します。

getMPCORB_and_mpc2edb_for_button

こちらのスクリプトも #17 のエラーハンドリング対応が必要になりますので、合わせてよろしくお願い致します。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
[anbai-add-errorhandling](https://github.com/coias/coias-front-app/tree/anbai-add-errorhandling)ブランチにて、
<img width="425" alt="スクリーンショット 2022-06-24 12 59 03" src="https://user-images.githubusercontent.com/97570265/175459546-8fc88ead-d304-4f64-9836-2a949cd82986.png">
この位置にボタンを追加し、指定のスクリプトに対応させました。

今後エラーハンドリングについては、このブランチにて更新させて頂きます。

**Comment by COIAS-program** [comment]
@AnbaiAnbai
ご対応いただきありがとうございます。
ファイル選択モーダルに「小惑星データ更新」ボタンが追加されていること、同ボタンを押すとgetMPCORB_and_mpc2edb_for_button beginsスクリプトが走ることを確かめました。

ただし、このボタンを押した時に走るスクリプトもエラーハンドリングの対象です。
例えばネットに繋いでいない時にこのスクリプトを走らせるとエラーが出ますが、探索準備モードと同様にエラーモーダルを表示させるようにお願い致します。

**Comment by COIAS-program** [comment]
anbai-add-errorhandlingブランチで修正されていることを確認致しました。
issueを閉じます。
