### ISSUE TITLE
エラーの通知について

### ISSUE THREAD

**Issue by Mizunanari** [coias/coias-back-app#17]
>例えばJPL horizonへの問い合わせでコケたり、ユーザーがそもそも正しい画像を選んでいない、などいろいろなエラーが発生する可能性があります。
その時に、フロント側を通してユーザーにエラーを知らせることを考えたときに、バックエンド側のスクリプトとしてどのような処理をすれば良いでしょうか?
例外送出でもすれば大丈夫でしょうか?
できればエラーの内容によってフロント側に出すメッセージも変えたいので、エラーの内容がフロントに伝わる書き方じゃないとダメだと思います。
ここは様々なエラー発生原因を洗い出さないといけないので完全に将来的な改良なのでまだやらなくて良いと思いますが、ご意見をお聞かせいただければと思います。

https://coiashq.slack.com/archives/C034Z0GDEBX/p1649137677217899

**Comment by COIAS-program** [comment]
エラーハンドリング時の大雑把な仕様と、エラーモーダルに表示して欲しいメッセージをまとめましたので、以下ワードファイルをご覧ください。
大雑把に書いてありますので、何か不明な点がありましたらお気軽にお知らせください。
[20220623エラーハンドリングメッセージまとめ.docx](https://github.com/coias/coias-back-app/files/8964595/20220623.docx)

エラーハンドリングに関してもう一点お願いがあります。
現在、探索モード後に「再描画」ボタンを押すと以下の3つのスクリプトを順番に叩く仕様になっているかと思います。
・prempedit
・prempedit3.py [新天体の通し番号]
・redisp
ここで[新天体の通し番号]とは「再描画」ボタンを押した後に現れるモーダルで聞かれて記入をした番号のことです。
叩くスクリプトが3つもあるとエラーハンドリング時に煩雑になるので、これらを AstsearchR_between_COIAS_and_ReCOIAS スクリプトにまとめました。
そこで、探索モードの「再描画」ボタンを押した後、モーダルで新天体の通し番号を指定した後に走るスクリプトを以下に変更願えないでしょうか?
AstsearchR_between_COIAS_and_ReCOIAS [新天体の通し番号]
[新天体の通し番号]は第二引数にて指定します。

**Comment by hasegawa-taisei** [comment]
@COIAS-program @urakawa-seitaro 
コミット : `d710ba1` (front) 
　　　　`007acc4` (back)
ブランチ : anbai-add-errorhandling (https://github.com/coias/coias-front-app/tree/anbai-add-errorhandling)
上記にて実装致しました。

フロント側では以下のような表示になります。

https://user-images.githubusercontent.com/105190797/176066461-db4c3d96-0c1c-4447-a326-60b1919b254c.mov

ご確認のほどよろしくお願いいたします。

**Comment by COIAS-program** [comment]
@hasegawa-taisei 
ご対応いただきありがとうございます。
探索準備モードにてエラーモーダルが表示されること、内容が正しいことを確認いたしました。
五月雨式になるかもですが、気がついたことを書かせていただきます。

エラーモーダルにて「Downloads」ボタンはログをダウンロードするボタンですが、「Downloads」だと何をダウンロードするか伝わらないと思います。
「Download log」など、ログをダウンロードできるボタンであることが伝わるような名称に変更をお願い致します。

**Comment by COIAS-program** [comment]
カレントディレクトリに存在しているlog.txtとダウンロードしているlog.txtが違っている気がします。
ダウンロードしているlog.txtはどうも内部にプールされている古いlog.txtみたいです。
必ずカレントに存在している最新のlog.txtをダウンロードするようにお願い致します。

**Comment by COIAS-program** [comment]
エラーハンドリングの対象になるスクリプトは、探索準備モードの5つのスクリプトのみではなく、「小惑星データ更新」ボタンを押した時のgetMPCORB_and_mpc2edb_for_buttonスクリプト (issue #16 にもコメント記載)、探索モードと再描画モードの間で走るAstsearchR_between_COIAS_and_ReCOIASスクリプト、手動測定モードの後に走るAstsearchR_after_manualスクリプト (手動測定実装中につきこのスクリプトを走らせる機能はまだ未実装)、レポートモードの前に走るAstsearchR_afterReCOIASスクリプトも対象です。
これらのスクリプト実行時にも、探索準備モードと同様にエラーが出たら同じような処理をするようにお願い致します。

**Comment by COIAS-program** [comment]
探索準備モードにおいても、全自動処理をして5つのスクリプトをまとめて自動実行した際にはエラーハンドリングが全くできていません。
もちろん全自動処理でもエラーが出たときはエラーモーダルを表示させてください。
仕様書にも書きましたが、全自動処理においてエラーが出た際は、5つのスクリプトのうちエラーが出たスクリプトが終了した時点で処理を中断させるようにお願い致します。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
コメントありがとうございます。
上記コメントに

- coias-front-app 
     ブランチ：anbai-add-errorhandling
      コミット：https://github.com/coias/coias-front-app/commit/371f03332e9d54d7300aa8f7e866b50482b5a1b6

- coias-back-app : 
      ブランチ：main
      コミット：https://github.com/coias/coias-back-app/commit/9e9b1704e76ea9aa71d3bb1bfb3889b7b491da28

にて対応させて頂きました。
確認よろしくお願い致します。

また、

>  3. astroquery.jplhorizonで何らかの理由でコケてタイムアウト

について、こちらでエラーをわざと出しデバッグをすることができませんでした。
現状すべてのエラーメッセージを強制的に出し、文字が正しいことだけを確認いたしました。

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
ご対応いただきありがとうございます。
ほとんど問題ないことを確認致しました。

一点だけ要望なのですが、レポートモードの直前処理でエラーが出た時、モーダルを閉じた後にもレポート前処理(AstsearchR_afterReCOIAS)をやり直せるように、レポートモードの右側、「Download send_mpc」ボタンの上くらい?に「レポート作成をやり直す」ボタンを置いて、それを押すとAstsearchR_afterReCOIASが走るようにするのはいかがでしょうか?
実際に、エラーが出なくともweb版findOrbへの問い合わせに失敗して軌道情報を取得できないこともあり(その場合でもバックアップのデスクトップfindOrbが走ってエラーは出ないが軌道情報は手に入らない)、やり直したい時はあるので。
再描画モードおよび手動測定の再描画モードでも「やり直し」ボタンがあってエラーが出た時にやり直すことができるので、レポートモードも同様にした方が良いと思います。

あともう一点、anbai-add-errorhandlingブランチでは再描画モードにてredisp.txtではなくdisp.txtが全て描画されているようです。(再描画モードで描画されるのはredisp.txtの中身のみ)
元々のmainブランチではきちんとredisp.txtのみが描画されるようになっていたと思いますが、mergeの際にバグを再輸入しないようにお気をつけください。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
確認ありがとうございます。
「レポート作成をやり直すボタン」を写真の位置に追加させて頂きました。
また、redispの件につきまして、気がつきませんでした、ありがとうございます。
このissueが閉じ、mergeする際に慎重に行いたいと思います。

![スクリーンショット 2022-07-12 8 48 51](https://user-images.githubusercontent.com/97570265/178377517-571d6d22-7d12-4a7c-9d2a-4f6b63aa0283.png)

**Comment by COIAS-program** [comment]
@AnbaiAnbai 
ご対応いただきありがとうございました。
僕が確認した範囲では、エラーハンドリングの実装はこれで完了で良いと思います。
mainブランチへのmergeをお願い致します。
また(バックエンド側も含めて)バグが出る可能性はありますが、一旦issueは閉じ、今後何かあったらslackなどで相談しましょう。

探索モードなどGUI部分でのエラーハンドリング(主にはredisp.txtなどの必要なファイルが無い場合の対処)もしなければいけませんが、これは[こちらのisssue](https://github.com/coias/coias-front-app/issues/67)とも関連がありますので、また議論しながら決めていきましょう。

**Comment by AnbaiAnbai** [comment]
@COIAS-program 
確認ありがとうございます。
frontをmainにmergeしました。
