### ISSUE TITLE
prempsearchCの分割方法について

### ISSUE THREAD

**Issue by Mizunanari** [coias/coias-back-app#18]
[Sugiura Keisuke](https://app.slack.com/team/U026MKNMH3M) 
>エラーハンドリングについて、API側にはシェルスクリプト のexitで返却コードを通知することになるかと思います。
現状、prempsearchCスクリプトに関しては、P_C_SPLIT_LINEまでとあととで分割して実行しているかと思いますが、この方法で返却コードを通知しようと思うと元のprempsearchCスクリプトに2回exit文を書く必要があるかと思います。
GUI COIASだけ見ると必ずP_C_SPLIT_LINEで分割するので問題ないように見えますが、同じスクリプトをオリジナルCOIASで走らせたとき明らかに問題になります(回避する方法はあるのかもしれませんが、多分手間)。
今後の保守管理を考えると、オリジナルCOIASとGUI COIASはなるべく同じスクリプトにしておきたいと考えています。
そこで提案なのですが、prempsearchCスクリプトを明示的にprempsearchC-beforeスクリプトとprempsearchC-afterスクリプトに分割し、それらをそれぞれ軌道取得(確定番号)、軌道取得(仮符号)ボタンで走らせるようにお願いできないでしょうか?
せっかくAPI側で分割する処理を実装していただいたところ申し訳ないのですが、ご確認をお願いできますと幸いです。

**Comment by COIAS-program** [comment]
prempsearchCを2つに分割し、さらにmain.pyを編集してそれぞれを呼び出すように変更しました。
main.pyの他の部分を参考にして編集を行い、また自分の環境で問題なく動くことは確認致しましたが、
main.pyのprempsearchC-beforeとafterをご覧いただき、書き方などに問題がないかご確認をお願いできますでしょうか?
