### ISSUE TITLE
localhostではなく127.0.0.1をブラウザで開いて使った場合にCORSのエラーがでる

### ISSUE THREAD

**Issue by kn1cht** [coias/coias-back-app#24]
# TL;DR
- http://127.0.0.1:3000 など，localhostではないoriginにアクセスして使うと，ファイルアップロード時にエラーが出ます
- Access-Control-Allow-Originがlocalhostのみになっているため，CORSエラーが出ているようです

# 現象
http://127.0.0.1:3000 でCOIASのGUIにアクセスし，ファイルを開く操作をすると「ファイルアップロードでエラーが発生しました。ファイルアップロードに失敗しました。」とのエラーが出ました．
このときコンソールを見ると，CORSエラーが発生していました．

```
127.0.0.1/:1 Access to XMLHttpRequest at 'http://localhost:8000/deletefiles' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
127.0.0.1/:1 Access to XMLHttpRequest at 'http://localhost:8000/uploadfiles/' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

一方， http://localhost:3000 にアクセスした場合は正常に動作しました．

# 考えられる原因
## CORSエラーの原因
バックエンドの`allow_origins`にlocalhostのみが指定されています．localhostと127.0.0.1はどちらもローカルホストですが，ブラウザは別originと見なすようなので，後者からアクセスするとCORSエラーになると考えられます．

https://github.com/coias/coias-back-app/blob/ec4d465d0187aad5bb5189415c939a77422faf9a/API/main.py#L31-L42

## http://127.0.0.1:3000 にアクセスしてしまった原因
Docker Desktopのコンテナ一覧で，PORT(S)に示されたリンクからコンテナがホスト側に公開するポートをブラウザで開ける機能があります．このリンクが127.0.0.1のものになっており，クリックして飛ぶと上記のエラーが生じました．

![image](https://user-images.githubusercontent.com/16277200/205533155-501184bf-79b0-4fd6-b789-77b0fa113b76.png)

このportsは`coias-docker-compose/docker-compose.yml`に指定されたものです．

https://github.com/coias/coias-docker-compose/blob/153fa8bc9bede59992b7a5ed2a09a6858e477596/docker-compose.yml#L4-L10

# 対応策の案
## http://127.0.0.1:3000 にアクセスされにくいようにする

クロスドメイン状態が起きないよう，ユーザが127.0.0.1を使わないようにする案です．
ドキュメントに127.0.0.1を経由しないような注意書きをしたり，（可能であれば）`docker-compose.yml`のアドレス指定をなくすなどの方法があります．

```diff
   front-app:
     container_name: coias-front-container
     image: ghcr.io/coias/coias-front-app:latest
     ports:
-      - 127.0.0.1:3000:3000
+      - 3000:3000
     tty: true
```

## Access-Control-Allow-Originの設定を追加する
`allow_origins`に http://127.0.0.1:3000 を追加してしまう案です．

もちろん，今後COIASをローカル実行するのではなくサーバに公開する場合は，改めてCORS設定が必要になります．

**Comment by AnbaiAnbai** [comment]
@kn1cht 
丁寧なご指摘と対策案までありがとうございました。

一旦、Access-Control-Allow-Originの設定を追加する方向で対策させていただきました。
ありがとうございました。

**Comment by kn1cht** [comment]
さっそくのご対応ありがとうございます！
127.0.0.1にアクセスした場合でもAPI処理が走ることを確認致しました．
